[package]
name = "keycode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
dirs = "5.0.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.7"
